// Generated by CoffeeScript 2.7.0
  //###############################################################################
import {
  addModulesToDebug
} from "thingy-debug";

//###############################################################################
addModulesToDebug({
  // cliargumentsmodule: true
  // configmodule: true
  mainprocessmodule: true,
  pathhandlermodule: true
});

// startupmodule: true
