// Generated by CoffeeScript 2.7.0
//#############################################################################
//region debug
var log, olog;

import {
  createLogFunctions
} from "thingy-debug";

({log, olog} = createLogFunctions("mainprocessmodule"));

import * as cfg from "./configmodule.js";

import * as pathHandler from "./pathhandlermodule.js";

import * as translator from "./translationmodule.js";

//#############################################################################
export var execute = function(e) {
  log("execute");
  pathHandler.digestInputArgument(e.input);
  pathHandler.digestOutputArgument(e.output);
  translator.translateAllFiles();
};
