// Generated by CoffeeScript 2.7.0
//#############################################################################
//region debug
var findRelevantFiles, isDirectory, isFile, isRelevantFile, log, olog, outputs, sourceFileEnding, sources;

import {
  createLogFunctions
} from "thingy-debug";

({log, olog} = createLogFunctions("pathhandlermodule"));

import * as pathModule from "path";

import fs from "fs";


//###########################################################
sources = null;

outputs = null;

//###########################################################
sourceFileEnding = ".spec.js";

//###########################################################
export var digestInputArgument = function(input) {
  var inputAbsolute;
  log("digestInputArgument");
  if (pathModule.isAbsolute(input)) {
    inputAbsolute = input;
  } else {
    inputAbsolute = pathModule.resolve(process.cwd(), input);
  }
  if (!fs.existsSync(inputAbsolute)) {
    throw new Error(`Specified input path does not exist! (${inputAbsolute})`);
  }
  if (isDirectory(inputAbsolute)) {
    sources = findRelevantFiles(inputAbsolute);
  } else {
    sources = [inputAbsolute];
  }
  olog({sources});
};


//###########################################################
export var digestOutputArgument = function(output) {
  log("digestOutputArgument");
};

//###########################################################
findRelevantFiles = function(path) {
  var allEntries, allRelevant, entry, entryAbsolute, i, len;
  log("findRelevantFiles");
  allEntries = fs.readdirSync(path);
  allRelevant = [];
  for (i = 0, len = allEntries.length; i < len; i++) {
    entry = allEntries[i];
    entryAbsolute = pathModule.resolve(path, entry);
    if (isRelevantFile(entryAbsolute)) {
      allRelevant.push(entryAbsolute);
    }
  }
  return allRelevant;
};

isRelevantFile = function(path) {
  log("isRelevantFile");
  if (!isFile(path)) {
    return false;
  }
  if (!path.endsWith(sourceFileEnding)) {
    return false;
  }
  return true;
};

//###########################################################
isDirectory = function(path) {
  var err, stat;
  try {
    stat = fs.statSync(path);
    return stat.isDirectory();
  } catch (error) {
    err = error;
    //# probably does not exist
    return false;
  }
};

isFile = function(path) {
  var err, stat;
  try {
    stat = fs.statSync(path);
    return stat.isFile();
  } catch (error) {
    err = error;
    //# probably does not exist
    return false;
  }
};
