// Generated by CoffeeScript 2.7.0
//#############################################################################
//region debug
var errLog, log, olog, successLog;

import {
  createLogFunctions
} from "thingy-debug";

({log, olog} = createLogFunctions("startupmodule"));

import c from 'chalk';

import * as main from "./mainprocessmodule.js";

import * as argsModule from "./cliargumentsmodule.js";

//endregion

//#############################################################################
//region internal variables
errLog = function(arg) {
  return console.log(c.red(arg));
};

successLog = function(arg) {
  return console.log(c.green(arg));
};

//endregion

//#############################################################################
export var cliStartup = async function() {
  var e, err;
  log("cliStartup");
  try {
    e = argsModule.extractArguments();
    await main.execute(e);
    return successLog('All done!');
  } catch (error) {
    err = error;
    errLog("Error!");
    errLog(err);
    if (err.stack) {
      errLog(err.stack);
    }
    return process.exit(-1);
  }
};
